workflows:
  ios-workflow:
    name: iOS Build
    environment:
      xcode: latest
    scripts:
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --workspace "jsb-default/frameworks/runtime-src/proj.ios_mac/hotfiregame.xcodeproj" \
            --scheme "hotfiregame"
    artifacts:
      - build/ios/ipa/*.ipa
